repos:
  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.10.1
    hooks:
      - id: check-autopkg-recipes
        args: [
            "--recipe-prefix=com.github.ucam-apple-support",
            "--override-prefix=local.",
            "--strict",
            "--",
        ]
      - id: forbid-autopkg-overrides
        exclude: ^RecipeOverrides/
      - id: forbid-autopkg-trust-info
        exclude: ^RecipeOverrides/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-yaml
    - id: trailing-whitespace
      args: ["--markdown-linebreak-ext=md"]
  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
  - repo: https://github.com/pycqa/pylint
    rev: v2.8.3
    hooks:
    - id: pylint
